# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1149, 844)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.port_layout = QtWidgets.QHBoxLayout()
        self.port_layout.setObjectName("port_layout")
        self.serialport_text = QtWidgets.QLabel(self.layoutWidget)
        self.serialport_text.setObjectName("serialport_text")
        self.port_layout.addWidget(self.serialport_text)
        self.serialport_combox = QtWidgets.QComboBox(self.layoutWidget)
        self.serialport_combox.setObjectName("serialport_combox")
        self.port_layout.addWidget(self.serialport_combox)
        self.verticalLayout_3.addLayout(self.port_layout)
        self.baudrate_layout = QtWidgets.QHBoxLayout()
        self.baudrate_layout.setObjectName("baudrate_layout")
        self.baudrate_text = QtWidgets.QLabel(self.layoutWidget)
        self.baudrate_text.setObjectName("baudrate_text")
        self.baudrate_layout.addWidget(self.baudrate_text)
        self.baudrate_combox = QtWidgets.QComboBox(self.layoutWidget)
        self.baudrate_combox.setObjectName("baudrate_combox")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_combox.addItem("")
        self.baudrate_layout.addWidget(self.baudrate_combox)
        self.verticalLayout_3.addLayout(self.baudrate_layout)
        self.parity_layout = QtWidgets.QHBoxLayout()
        self.parity_layout.setObjectName("parity_layout")
        self.parity_text = QtWidgets.QLabel(self.layoutWidget)
        self.parity_text.setObjectName("parity_text")
        self.parity_layout.addWidget(self.parity_text)
        self.parity_combox = QtWidgets.QComboBox(self.layoutWidget)
        self.parity_combox.setObjectName("parity_combox")
        self.parity_combox.addItem("")
        self.parity_combox.addItem("")
        self.parity_combox.addItem("")
        self.parity_combox.addItem("")
        self.parity_combox.addItem("")
        self.parity_layout.addWidget(self.parity_combox)
        self.verticalLayout_3.addLayout(self.parity_layout)
        self.databit_layout = QtWidgets.QHBoxLayout()
        self.databit_layout.setObjectName("databit_layout")
        self.databit_text = QtWidgets.QLabel(self.layoutWidget)
        self.databit_text.setObjectName("databit_text")
        self.databit_layout.addWidget(self.databit_text)
        self.databit_combox = QtWidgets.QComboBox(self.layoutWidget)
        self.databit_combox.setObjectName("databit_combox")
        self.databit_combox.addItem("")
        self.databit_combox.addItem("")
        self.databit_combox.addItem("")
        self.databit_combox.addItem("")
        self.databit_layout.addWidget(self.databit_combox)
        self.verticalLayout_3.addLayout(self.databit_layout)
        self.stopbit_layout = QtWidgets.QHBoxLayout()
        self.stopbit_layout.setObjectName("stopbit_layout")
        self.stopbit_text = QtWidgets.QLabel(self.layoutWidget)
        self.stopbit_text.setObjectName("stopbit_text")
        self.stopbit_layout.addWidget(self.stopbit_text)
        self.stopbit_combox = QtWidgets.QComboBox(self.layoutWidget)
        self.stopbit_combox.setObjectName("stopbit_combox")
        self.stopbit_combox.addItem("")
        self.stopbit_combox.addItem("")
        self.stopbit_combox.addItem("")
        self.stopbit_layout.addWidget(self.stopbit_combox)
        self.verticalLayout_3.addLayout(self.stopbit_layout)
        self.open_serial_button = QtWidgets.QPushButton(self.layoutWidget)
        self.open_serial_button.setObjectName("open_serial_button")
        self.verticalLayout_3.addWidget(self.open_serial_button)
        self.refresh_serial_info = QtWidgets.QPushButton(self.layoutWidget)
        self.refresh_serial_info.setObjectName("refresh_serial_info")
        self.verticalLayout_3.addWidget(self.refresh_serial_info)
        self.clear_recv_data = QtWidgets.QPushButton(self.layoutWidget)
        self.clear_recv_data.setObjectName("clear_recv_data")
        self.verticalLayout_3.addWidget(self.clear_recv_data)
        self.stop_show_data = QtWidgets.QPushButton(self.layoutWidget)
        self.stop_show_data.setObjectName("stop_show_data")
        self.verticalLayout_3.addWidget(self.stop_show_data)
        self.save_to_file_button = QtWidgets.QPushButton(self.layoutWidget)
        self.save_to_file_button.setObjectName("save_to_file_button")
        self.verticalLayout_3.addWidget(self.save_to_file_button)
        self.clear_hex_layout = QtWidgets.QHBoxLayout()
        self.clear_hex_layout.setObjectName("clear_hex_layout")
        self.recv_hex_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.recv_hex_checkbox.setObjectName("recv_hex_checkbox")
        self.clear_hex_layout.addWidget(self.recv_hex_checkbox)
        self.verticalLayout_3.addLayout(self.clear_hex_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.recv_data_browser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.recv_data_browser.setObjectName("recv_data_browser")
        self.horizontalLayout_2.addWidget(self.recv_data_browser)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 7)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.auto_send_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.auto_send_checkbox.setObjectName("auto_send_checkbox")
        self.verticalLayout.addWidget(self.auto_send_checkbox)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.auto_send_time = QtWidgets.QLineEdit(self.layoutWidget1)
        self.auto_send_time.setObjectName("auto_send_time")
        self.gridLayout.addWidget(self.auto_send_time, 0, 0, 1, 1)
        self.auto_send_text = QtWidgets.QLabel(self.layoutWidget1)
        self.auto_send_text.setObjectName("auto_send_text")
        self.gridLayout.addWidget(self.auto_send_text, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.clear_after_send_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.clear_after_send_checkbox.setObjectName("clear_after_send_checkbox")
        self.verticalLayout.addWidget(self.clear_after_send_checkbox)
        self.send_hex_layout = QtWidgets.QHBoxLayout()
        self.send_hex_layout.setObjectName("send_hex_layout")
        self.send_hex_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.send_hex_checkbox.setObjectName("send_hex_checkbox")
        self.send_hex_layout.addWidget(self.send_hex_checkbox)
        self.verticalLayout.addLayout(self.send_hex_layout)
        self.clear_send_edit_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.clear_send_edit_btn.setObjectName("clear_send_edit_btn")
        self.verticalLayout.addWidget(self.clear_send_edit_btn)
        self.send_data_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.send_data_button.setObjectName("send_data_button")
        self.verticalLayout.addWidget(self.send_data_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.send_edit_tab = QtWidgets.QTabWidget(self.layoutWidget1)
        self.send_edit_tab.setObjectName("send_edit_tab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.send_edit = QtWidgets.QTextEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_edit.sizePolicy().hasHeightForWidth())
        self.send_edit.setSizePolicy(sizePolicy)
        self.send_edit.setObjectName("send_edit")
        self.horizontalLayout_3.addWidget(self.send_edit)
        self.send_edit_tab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.send_edit_tab.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.send_edit_tab)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 7)
        self.horizontalLayout_4.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1149, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.send_edit_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "泡面串口助手"))
        self.serialport_text.setText(_translate("MainWindow", "端口："))
        self.baudrate_text.setText(_translate("MainWindow", "波特率："))
        self.baudrate_combox.setItemText(0, _translate("MainWindow", "9600"))
        self.baudrate_combox.setItemText(1, _translate("MainWindow", "115200"))
        self.baudrate_combox.setItemText(2, _translate("MainWindow", "1200"))
        self.baudrate_combox.setItemText(3, _translate("MainWindow", "1800"))
        self.baudrate_combox.setItemText(4, _translate("MainWindow", "2400"))
        self.baudrate_combox.setItemText(5, _translate("MainWindow", "3600"))
        self.baudrate_combox.setItemText(6, _translate("MainWindow", "4800"))
        self.baudrate_combox.setItemText(7, _translate("MainWindow", "7200"))
        self.baudrate_combox.setItemText(8, _translate("MainWindow", "14400"))
        self.baudrate_combox.setItemText(9, _translate("MainWindow", "19200"))
        self.baudrate_combox.setItemText(10, _translate("MainWindow", "28800"))
        self.baudrate_combox.setItemText(11, _translate("MainWindow", "38400"))
        self.baudrate_combox.setItemText(12, _translate("MainWindow", "57600"))
        self.baudrate_combox.setItemText(13, _translate("MainWindow", "230400"))
        self.parity_text.setText(_translate("MainWindow", "校验位："))
        self.parity_combox.setItemText(0, _translate("MainWindow", "无校验"))
        self.parity_combox.setItemText(1, _translate("MainWindow", "1 校验"))
        self.parity_combox.setItemText(2, _translate("MainWindow", "0 校验"))
        self.parity_combox.setItemText(3, _translate("MainWindow", "奇校验"))
        self.parity_combox.setItemText(4, _translate("MainWindow", "偶校验"))
        self.databit_text.setText(_translate("MainWindow", "数据位："))
        self.databit_combox.setItemText(0, _translate("MainWindow", "8"))
        self.databit_combox.setItemText(1, _translate("MainWindow", "5"))
        self.databit_combox.setItemText(2, _translate("MainWindow", "6"))
        self.databit_combox.setItemText(3, _translate("MainWindow", "7"))
        self.stopbit_text.setText(_translate("MainWindow", "停止位："))
        self.stopbit_combox.setItemText(0, _translate("MainWindow", "1"))
        self.stopbit_combox.setItemText(1, _translate("MainWindow", "1.5"))
        self.stopbit_combox.setItemText(2, _translate("MainWindow", "2"))
        self.open_serial_button.setText(_translate("MainWindow", "打开串口"))
        self.refresh_serial_info.setText(_translate("MainWindow", "刷新串口信息"))
        self.clear_recv_data.setText(_translate("MainWindow", "清空接收区"))
        self.stop_show_data.setText(_translate("MainWindow", "停止显示"))
        self.save_to_file_button.setText(_translate("MainWindow", "保存数据"))
        self.recv_hex_checkbox.setText(_translate("MainWindow", "十六进制显示"))
        self.auto_send_checkbox.setText(_translate("MainWindow", "自动发送"))
        self.auto_send_time.setText(_translate("MainWindow", "1000"))
        self.auto_send_text.setText(_translate("MainWindow", "ms"))
        self.clear_after_send_checkbox.setText(_translate("MainWindow", "发送完清空"))
        self.send_hex_checkbox.setText(_translate("MainWindow", "十六进制发送"))
        self.clear_send_edit_btn.setText(_translate("MainWindow", "清空发送区"))
        self.send_data_button.setText(_translate("MainWindow", "发送数据"))
        self.send_edit_tab.setTabText(self.send_edit_tab.indexOf(self.tab), _translate("MainWindow", "单一数据"))
        self.send_edit_tab.setTabText(self.send_edit_tab.indexOf(self.tab_2), _translate("MainWindow", "预留tab"))

